use_frameworks!

platform :ios, '10.0'

target 'WOCDebugKit_Example' do
  pod 'WOCDebugKit', :path => '../'
  pod 'Masonry', '1.1.0', :modular_headers => true
  pod 'FMDB'
  pod 'LookinServer', :configurations => ['Debug'] #调试工具
  pod 'LSTableTool', :git => 'git@github.com:Amberbady/LSTableTool.git' , :commit => '6f751a8'
  target 'WOCDebugKit_Tests' do
    inherit! :search_paths

    
  end
end
